--- #YAML:1.0
name:               Bootylicious-Parser-Md
version:            0.990101
abstract:           Md plugin for bootylicious
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Mojo:            0.999909
    perl:            5.008001
    Text::Markdown:  0
resources:
    homepage:    http://getbootylicious.org
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/vti/bootylicious-parser-md/tree/master
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
